title: paly.win
description: >
  A Palo Alto High School site that's mobile friendly, slimmed down, and with a better design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paly.win" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-minifier
sass:
  style: compressed