title: paly.win
description: >
  A Palo Alto High School site that's mobile friendly, slimmed down, and with a better design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paly.win" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-minifier
sass:
  style: compressed
algolia:
  application_id: O3D9OIP9FH
  search_only_api_key: d15952a25b7c2635422e34d2e116e9ce
  index_name: paly.win
  nodes_to_index: 'p,h2,h3,h4,li,h5'
  files_to_exclude: ['search.html']